[profile.default]
src = "src"
libs = ["lib"]

# Build directories
out = "build/out"
cache_path = "build/cache"

# Solidity
optimizer = true
optimizer_runs = 200
evm_version = "paris"
solc_version = "0.8.27"

# Remappings
remappings = [
    # Local files
    "@/=src/",

    # Library
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# RPC urls
[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"

# Etherscan keys
[etherscan]
bsc_testnet = {key = "${BSCSCAN_API_KEY}"}
